# Generated by Django 3.1.5 on 2021-01-11 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('viewz_book', 'View Book'), ('review', 'Review')]},
        ),
        migrations.AlterModelOptions(
            name='chapter',
            options={'permissions': [('viewz_chapter', 'View Chapter')]},
        ),
        migrations.AlterModelOptions(
            name='paragraph',
            options={'permissions': [('viewz_paragraph', 'View Paragraph')]},
        ),
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
